# Generated by Django 3.2.9 on 2021-12-06 13:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gallery.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('urlCode', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(default='some_artwork', max_length=50)),
                ('artId', models.CharField(db_index=True, default=gallery.utils.getArtId, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username', regex='^(?=.{8}$)(?![0-9])[a-zA-Z0-9]+$')])),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_transit', models.DateTimeField(default=django.utils.timezone.now)),
                ('a_type', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('1', 'gallery property'), ('0', 'no owner')], default='1', max_length=2)),
                ('info', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='some_artist', max_length=35, null=True)),
                ('urlCode', models.IntegerField(db_index=True, unique=True)),
                ('y_born', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('y_pass', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
                ('art_num', models.PositiveIntegerField(default=0)),
                ('v_factor', models.PositiveIntegerField(default=0)),
                ('areas', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GA_Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'destroyed'), ('1', 'in gallery'), ('2', 'in transit'), ('3', 'in borrow'), ('4', 'sold')], default='1', max_length=2)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.art')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='some_gallery', max_length=30, null=True)),
                ('urlCode', models.IntegerField(db_index=True, unique=True)),
                ('galleryId', models.CharField(default=gallery.utils.getGalleryId, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username', regex='^(?=.{10,10}$)(?![0-9])[A-Z0-9]+$')])),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('0', 'closed'), ('1', 'open'), ('2', 'under construction'), ('3', 'destroyed')], default='1', max_length=2)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('art_num', models.PositiveIntegerField(default=0)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('info', models.FileField(blank=True, upload_to='')),
                ('art', models.ManyToManyField(through='gallery.GA_Collection', to='gallery.Art')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='warehouse*', max_length=30, null=True)),
                ('urlCode', models.IntegerField(db_index=True, unique=True)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('0', 'closed'), ('1', 'open'), ('2', 'under construction'), ('3', 'destroyed')], default='1', max_length=2)),
                ('art_num', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GW_Attach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'destroyed'), ('1', 'in use'), ('2', 'in construction'), ('3', 'destroyed')], default='1', max_length=2)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='GU_Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('0', 'owner'), ('1', 'manager'), ('2', 'staff')], max_length=2)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='staff',
            field=models.ManyToManyField(through='gallery.GU_Relation', to='user.User'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='warehouse',
            field=models.ManyToManyField(through='gallery.GW_Attach', to='gallery.Warehouse'),
        ),
        migrations.AddField(
            model_name='ga_collection',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery'),
        ),
        migrations.AddField(
            model_name='ga_collection',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.warehouse'),
        ),
        migrations.AddField(
            model_name='art',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.artist'),
        ),
    ]
