# Generated by Django 3.2.9 on 2021-12-06 13:25

from django.db import migrations, models
import gallery.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='urlCode',
            field=models.IntegerField(db_index=True, default=gallery.utils.getArtCode, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='urlCode',
            field=models.IntegerField(db_index=True, default=gallery.utils.getArtistCode, unique=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='urlCode',
            field=models.IntegerField(db_index=True, unique=True, verbose_name=gallery.utils.getGalleryCode),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='urlCode',
            field=models.IntegerField(db_index=True, default=gallery.utils.getWarehouseCode, unique=True),
        ),
    ]
