# Generated by Django 3.2.9 on 2021-12-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20211206_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='a_type',
            new_name='type',
        ),
    ]
