# Generated by Django 3.2.9 on 2021-12-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_a_type_art_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='info',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
