# Generated by Django 3.2.9 on 2021-12-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20211228_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='warehouse_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
