# Generated by Django 3.2.9 on 2021-12-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_gallery_warehouse_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='ga_collection',
            name='status',
            field=models.CharField(choices=[('0', 'destroyed'), ('1', 'in gallery'), ('2', 'in transit'), ('3', 'in borrow'), ('4', 'borrowed'), ('5', 'sold')], default='1', max_length=2),
        ),
    ]
