# Generated by Django 3.2.9 on 2021-12-31 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20211228_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='warehouse',
            new_name='warehouses',
        ),
        migrations.RemoveField(
            model_name='art',
            name='artist',
        ),
        migrations.CreateModel(
            name='AA_creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(blank=True, max_length=50, null=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.art')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.artist')),
            ],
        ),
        migrations.AddField(
            model_name='art',
            name='artists',
            field=models.ManyToManyField(through='gallery.AA_creation', to='gallery.Artist'),
        ),
    ]
