# Generated by Django 3.2.9 on 2021-12-31 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20211231_0849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GA_Collection',
            new_name='WA_Collection',
        ),
        migrations.RenameField(
            model_name='gu_relation',
            old_name='relation',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='gu_relation',
            old_name='staff',
            new_name='staff_member',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='art',
        ),
        migrations.AddField(
            model_name='gu_relation',
            name='privilege',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='arts',
            field=models.ManyToManyField(through='gallery.WA_Collection', to='gallery.Art'),
        ),
        migrations.AlterField(
            model_name='gu_relation',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.warehouse'),
        ),
    ]
