# Generated by Django 3.2.9 on 2022-01-12 08:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gallery.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20211231_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='artId',
        ),
        migrations.AlterField(
            model_name='art',
            name='id',
            field=models.CharField(db_index=True, default=gallery.utils.getArtId, max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username', regex='^(?=.{8}$)(?![0-9])[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='gu_relation',
            name='privilege',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gu_relation',
            name='role',
            field=models.CharField(choices=[('0', 'owner'), ('1', 'administrator'), ('2', 'manager'), ('3', 'staff')], default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='gu_relation',
            name='warehouse',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.warehouse'),
        ),
    ]
