# Generated by Django 3.2.9 on 2022-01-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20220112_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='wa_collection',
            name='rack',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
