# Generated by Django 3.2.9 on 2022-01-18 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_wa_collection_rack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='id',
            field=models.CharField(db_index=True, default='', max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username', regex='^(?=.{8}$)(?![0-9])[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='art',
            name='info',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='art',
            name='urlCode',
            field=models.IntegerField(db_index=True, default=0, unique=True),
        ),
    ]
