# Generated by Django 3.2.9 on 2022-01-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20220118_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='author',
            field=models.CharField(default='', max_length=48),
        ),
    ]
