# Generated by Django 3.2.9 on 2022-01-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_art_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nothing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='test as warehouse', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='gw_attach',
            name='status',
            field=models.CharField(choices=[('0', 'closed'), ('1', 'open'), ('2', 'under construction'), ('3', 'destroyed')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='arts',
            field=models.ManyToManyField(related_name='whs', through='gallery.WA_Collection', to='gallery.Art'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='test_w',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.nothing'),
        ),
    ]
