# Generated by Django 3.2.9 on 2022-01-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20220119_1850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nothing',
            new_name='Nothings',
        ),
    ]
