# Generated by Django 3.2.9 on 2022-01-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_rename_nothing_nothings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='test_w',
        ),
        migrations.DeleteModel(
            name='Nothings',
        ),
    ]
