# Generated by Django 3.2.9 on 2022-01-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_auto_20220119_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='warehouses',
        ),
    ]
