# Generated by Django 3.2.9 on 2022-01-19 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_remove_gallery_warehouses'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.art'),
        ),
    ]
