# Generated by Django 3.2.9 on 2022-01-19 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_warehouse_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.art'),
        ),
    ]
