# Generated by Django 3.2.9 on 2022-01-19 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_alter_warehouse_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallery'),
        ),
    ]
