# Generated by Django 3.2.9 on 2022-01-19 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_alter_warehouse_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wa_collection',
            name='art',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gallery.art'),
        ),
    ]
