# Generated by Django 3.2.9 on 2022-01-21 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_artist'),
        ('gallery', '0021_alter_wa_collection_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_relation2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.PositiveSmallIntegerField(default=0, null=True)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Test_relation1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('0', 'owner'), ('1', 'administrator'), ('2', 'manager'), ('3', 'staff')], default='', max_length=2, null=True)),
                ('privilege', models.PositiveSmallIntegerField(default=0, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
