# Generated by Django 3.2.9 on 2022-01-23 07:42

import django.core.validators
from django.db import migrations, models
import gallery.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0022_test_relation1_test_relation2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='id',
            field=models.CharField(db_index=True, default=gallery.utils.getArtId, max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username', regex='^(?=.{8}$)(?![0-9])[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='art',
            name='urlCode',
            field=models.IntegerField(db_index=True, default=gallery.utils.getArtCode, unique=True),
        ),
        migrations.AddConstraint(
            model_name='gu_relation',
            constraint=models.UniqueConstraint(fields=('gallery', 'staff_member'), name='r_unique_gu'),
        ),
        migrations.AddConstraint(
            model_name='gu_relation',
            constraint=models.UniqueConstraint(fields=('warehouse', 'staff_member'), name='r_unique_wu'),
        ),
        migrations.AddConstraint(
            model_name='test_relation1',
            constraint=models.UniqueConstraint(fields=('gallery', 'staff_member'), name='t1_unique_gu'),
        ),
        migrations.AddConstraint(
            model_name='test_relation2',
            constraint=models.UniqueConstraint(fields=('warehouse', 'staff_member'), name='t2_unique_wu'),
        ),
    ]
