# Generated by Django 3.2.9 on 2022-01-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_artist'),
        ('gallery', '0023_auto_20220123_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='staff',
            field=models.ManyToManyField(through='gallery.Test_relation1', to='user.User'),
        ),
    ]
