# Generated by Django 3.2.9 on 2022-01-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_artist'),
        ('gallery', '0024_alter_gallery_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test_relation1',
            new_name='GU_new',
        ),
    ]
