# Generated by Django 3.2.9 on 2022-01-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_artist'),
        ('gallery', '0025_rename_test_relation1_gu_new'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test_relation2',
            new_name='WU_Relation',
        ),
    ]
