# Generated by Django 3.2.9 on 2022-01-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_artist'),
        ('gallery', '0026_rename_test_relation2_wu_relation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GU_Relation',
            new_name='GU_Relation_old',
        ),
    ]
