# Generated by Django 3.2.9 on 2022-01-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_artist'),
        ('gallery', '0027_rename_gu_relation_gu_relation_old'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GU_new',
            new_name='GU_Relation',
        ),
    ]
