# Generated by Django 3.2.9 on 2022-01-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_artist'),
        ('gallery', '0028_rename_gu_new_gu_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='staff',
            field=models.ManyToManyField(through='gallery.WU_Relation', to='user.User'),
        ),
    ]
