# Generated by Django 3.2.9 on 2022-01-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0029_warehouse_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='arts',
        ),
    ]
