# Generated by Django 3.2.9 on 2022-01-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0030_remove_warehouse_arts'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gu_relation',
            constraint=models.UniqueConstraint(fields=('gallery', 'staff_member'), name='unique_gu'),
        ),
    ]
