# Generated by Django 3.2.9 on 2022-01-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0031_gu_relation_unique_gu'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gu_relation',
            name='t1_unique_gu',
        ),
    ]
