# Generated by Django 3.2.9 on 2022-01-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0032_remove_gu_relation_t1_unique_gu'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wu_relation',
            constraint=models.UniqueConstraint(fields=('warehouse', 'staff_member'), name='unique_wu'),
        ),
    ]
