# Generated by Django 3.2.9 on 2022-01-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0033_wu_relation_unique_wu'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wu_relation',
            name='t2_unique_wu',
        ),
    ]
