# Generated by Django 3.2.9 on 2022-01-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0034_remove_wu_relation_t2_unique_wu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='status',
            field=models.CharField(choices=[('0', 'destroyed'), ('1', 'in gallery'), ('2', 'in transit'), ('3', 'in borrow'), ('4', 'borrowed'), ('5', 'sold')], default='1', max_length=2),
        ),
    ]
