# Generated by Django 3.2.9 on 2022-01-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0035_alter_art_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='status',
            field=models.CharField(choices=[('1', 'gallery property'), ('0', 'no owner')], default='1', max_length=2),
        ),
    ]
