# Generated by Django 3.2.9 on 2022-01-23 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0036_alter_art_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='rack',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='art',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.warehouse'),
        ),
        migrations.AlterField(
            model_name='art',
            name='status',
            field=models.CharField(choices=[('0', 'destroyed'), ('1', 'in gallery'), ('2', 'in transit'), ('3', 'in borrow'), ('4', 'borrowed'), ('5', 'sold')], default='1', max_length=2),
        ),
    ]
