# Generated by Django 3.2.9 on 2022-01-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0037_auto_20220123_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WA_Collection',
        ),
    ]
