# Generated by Django 3.2.9 on 2022-01-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0038_delete_wa_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GW_Attach',
        ),
    ]
