# Generated by Django 3.2.9 on 2022-01-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0039_delete_gw_attach'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gu_relation_old',
            name='r_unique_gu',
        ),
    ]
