# Generated by Django 3.2.9 on 2022-01-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0040_remove_gu_relation_old_r_unique_gu'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gu_relation_old',
            constraint=models.UniqueConstraint(fields=('gallery', 'warehouse', 'staff_member'), name='r_unique_gwu'),
        ),
    ]
