# Generated by Django 3.2.9 on 2022-01-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0041_gu_relation_old_r_unique_gwu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='rack',
            field=models.CharField(default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='gallery.gallery'),
        ),
    ]
