# Generated by Django 3.2.9 on 2022-02-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_artist'),
        ('gallery', '0042_auto_20220125_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='city',
        ),
        migrations.AddField(
            model_name='gallery',
            name='asdasdas',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='staff',
            field=models.ManyToManyField(related_name='galleries', through='gallery.GU_Relation', to='user.User'),
        ),
    ]
