# Generated by Django 3.2.9 on 2022-02-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0043_auto_20220220_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='asdasdas',
        ),
    ]
