# Generated by Django 3.2.9 on 2022-02-20 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_auto_20220220_0931'),
        ('gallery', '0044_remove_gallery_asdasdas'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.city'),
        ),
    ]
