# Generated by Django 3.2.9 on 2022-02-24 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0045_gallery_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='gu_relation',
            name='date_join',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wu_relation',
            name='date_join',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
