# Generated by Django 3.2.9 on 2022-03-07 07:38

from django.db import migrations, models
import gallery.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0046_auto_20220224_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='gu_relation',
            name='status',
            field=models.CharField(choices=[('0', '在线'), ('1', '离线'), ('2', '离职'), ('3', '出差')], default='1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='urlCode',
            field=models.IntegerField(db_index=True, default=gallery.utils.getGalleryCode, unique=True),
        ),
    ]
