# Generated by Django 3.2.9 on 2022-03-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0047_auto_20220307_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='wu_relation',
            name='status',
            field=models.CharField(choices=[('0', '在线'), ('1', '离线'), ('2', '离职'), ('3', '出差')], default='1', max_length=2, null=True),
        ),
    ]
