# Generated by Django 3.2.9 on 2022-03-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0048_wu_relation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gu_relation',
            name='role',
            field=models.CharField(choices=[('0', 'owner'), ('1', 'administrator'), ('2', 'manager'), ('3', 'staff')], default='3', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='gu_relation',
            name='status',
            field=models.CharField(choices=[('0', '在职'), ('1', '离职'), ('2', '出差'), ('3', '在线'), ('4', '离线')], default='0', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='wu_relation',
            name='status',
            field=models.CharField(choices=[('0', '在职'), ('1', '离职'), ('2', '出差'), ('3', '在线'), ('4', '离线')], default='0', max_length=2, null=True),
        ),
    ]
