name: jpt
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2021.10.8
  - libffi=3.4.2
  - openssl=3.0.0
  - pip=21.3.1
  - python=3.8.12
  - python_abi=3.8
  - setuptools=60.2.0
  - sqlite=3.37.0
  - tk=8.6.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
