# Generated by Django 3.2.9 on 2022-02-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('ascii', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('iso2', models.CharField(max_length=50)),
                ('iso3', models.CharField(max_length=50)),
                ('admin_name', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=50)),
            ],
        ),
    ]
