# Generated by Django 3.2.9 on 2022-02-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='city',
            name='admin_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='ascii',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='capital',
            field=models.CharField(choices=[('00', 'None'), ('01', 'admin'), ('02', 'Primary')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='city',
            name='iso2',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='city',
            name='iso3',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='city',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='city',
            name='lng',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
