# Generated by Django 3.2.9 on 2022-02-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_auto_20220220_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
