# Generated by Django 3.2.9 on 2022-02-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='capital',
            field=models.CharField(max_length=15),
        ),
    ]
