# Generated by Django 3.2.9 on 2022-02-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_alter_city_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='admin_name',
            field=models.CharField(max_length=50),
        ),
    ]
