# Generated by Django 3.2.9 on 2022-02-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_alter_city_admin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='ascii',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='capital',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
