# Generated by Django 3.2.9 on 2022-02-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0006_auto_20220220_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='capital',
            field=models.CharField(default='', max_length=50),
        ),
    ]
