# Generated by Django 3.2.9 on 2021-12-06 13:23

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import user.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='some_user', max_length=20)),
                ('urlCode', models.IntegerField(db_index=True, default=user.utils.getUserCode, unique=True)),
                ('username', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username', regex='^(?=.{6,20}$)(?![_0-9])(?!.*[_]{2})[a-zA-Z0-9_]+(?<![_])$')])),
                ('password', models.CharField(max_length=64)),
                ('sex', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
                ('areas', models.PositiveIntegerField(default=0)),
                ('info', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
